#!/usr/bin/env bash
# config nginx new
# shellcheck disable=SC2154
apt-get update
apt-get -y install nginx
sed -i "29 i \\\n\tadd_header X-Served-By $HOSTNAME;\n" \
    /etc/nginx/sites-available/default
service nginx restart
