#!/usr/bin/env bash
# Install and configure HAproxy
echo deb http://archive.ubuntu.com/ubuntu trusty-backports main universe | \
      tee /etc/apt/sources.list.d/backports.list
apt-get update
apt-get install -y haproxy -t trusty-backports
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sed -i "6 i \\\nENABLED=1\n" /etc/default/haproxy
sed -i "\$a\
listen backend *:80\n\
\tmode http\n\tbalance roundrobin\n\
\tserver 205-web-01 54.175.3.213:80 check\n\
\tserver 205-web-02 34.228.64.127:80 check\n" \
/etc/haproxy/haproxy.cfg
sudo service haproxy start
