#!/usr/bin/env bash
# This script does fizz/buzz
for num in {1..100}
do
    if [[ "($num%15)" -eq 0 ]]
    then
        echo "FizzBuzz"
    elif [[ "($num%3)" -eq 0 ]]
    then
        echo "Fizz"
    elif [[ "($num%5)" -eq 0 ]]
    then
        echo "Buzz"
    else
        echo "$num"
    fi
done
