#!/usr/bin/env bash
# change so that Nginx is running as the nginx user
pkill -9 apache2
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
service nginx restart
